Repository googleapis/java-speech, pull requests merged in 2020-12, with the labels that each got.

#375 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#376 samples: add recognize sample with profanity filter
  samples/snippets/src/main/java/com/example/speech/InfiniteStreamRecognize.java
  samples/snippets/src/main/java/com/example/speech/SpeechProfanityFilter.java
  samples/snippets/src/test/java/com/example/speech/SpeechProfanityFilterTest.java
Labels: api: speech, cla: yes, samples

#381 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#378 samples: refactor quickstart to use a gcs file
  samples/snippets/src/main/java/com/example/speech/QuickstartSample.java
Labels: api: speech, automerge, cla: yes

#383 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#393 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#395 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#394 samples: add multi region transcribe sample
  samples/snippets/src/main/java/com/example/speech/SpeechTranscribeMultiRegion.java
  samples/snippets/src/test/java/com/example/speech/SpeechTranscribeMultiRegionTest.java
Labels: api: speech, automerge, cla: yes, samples

#396 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#397 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full, merge
