Repository googleapis/java-speech, pull requests merged in 2020-08, with the labels that each got.

#248 chore: regenerate common templates
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  README.md
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechSmokeTest.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechSmokeTest.java
  synth.metadata
  synth.py
Labels: cla: yes, context: partial

#257 test: fix default GCS file for tests
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/it/ITSpeechTest.java
Labels: cla: yes

#249 samples: migrate samples from GoogleCloudPlatform/java-docs-samples /speech/beta
  samples/snippets/src/main/java/com/example/speech/RecognizeBeta.java
  samples/snippets/src/main/java/com/example/speech/SpeechAdaptation.java
  samples/snippets/src/test/java/com/example/speech/RecognizeBetaIT.java
  samples/snippets/src/test/java/com/example/speech/SpeechAdaptationTest.java
Labels: cla: yes

#258 chore: regenerate sample list
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#265 samples: add presubmit lint check
  .github/workflows/samples.yaml
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/dependencies.sh
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#266 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: speech, cla: yes, context: full
