Repository googleapis/java-speech, pull requests merged in 2020-09, with the labels that each got.

#267 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: speech, cla: yes, context: full

#274 chore: regenerate README
  README.md
  synth.metadata
Labels: api: speech, cla: yes, context: none

#277 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#290 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: speech, automerge, cla: yes

#295 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#297 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
