Repository googleapis/java-speech, pull requests merged in 2021-01, with the labels that each got.

#399 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#400 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#406 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#408 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#380 chore: migrate to microgenerator
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/package-info.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/GrpcSpeechCallableFactory.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/GrpcSpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStubSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/package-info.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/GrpcSpeechCallableFactory.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/GrpcSpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/SpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/SpeechStubSettings.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/MockSpeech.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/MockSpeechImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechClientTest.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockSpeech.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockSpeechImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechClientTest.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/CustomClassName.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/PhraseSetName.java
  synth.metadata
  synth.py
Labels: api: speech, cla: yes, context: full

#411 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: speech, automerge, cla: yes
