Repository googleapis/java-speech, pull requests merged in 2021-06, with the labels that each got.

#538 chore: change region
  samples/snippets/src/test/java/com/example/speech/SpeechModelAdaptationBetaTest.java
Labels: api: speech, cla: yes

#541 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#542 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#543 chore: release gapic-generator-java v1.0.10
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/AdaptationClientTest.java
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#544 samples: adds export to GCS sample
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/com/example/speech/ExportToStorageBeta.java
  samples/snippets/src/test/java/com/example/speech/ExportToStorageBetaTest.java
Labels: api: speech, cla: yes, samples

#549 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#553 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#554 chore: release gapic-generator-java v1.0.11
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechClientTest.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/AdaptationClientTest.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechClientTest.java
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#561 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#564 chore: release gapic-generator-java v1.0.13
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/CustomClassName.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LocationName.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/PhraseSetName.java
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#565 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#567 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full
