Repository googleapis/java-speech, pull requests merged in 2021-09, with the labels that each got.

#657 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: speech, automerge, context: full

#659 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: speech, automerge, context: full

#664 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: speech, context: full

#667 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: speech, automerge

#666 chore(java): update windows build
  .github/readme/synth.py
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  README.md
  synth.metadata
Labels: cla: yes, api: speech, automerge, context: full

#688 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: speech, automerge

#693 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: speech, automerge

#701 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: speech, automerge
