Repository googleapis/java-speech, pull requests merged in 2021-04, with the labels that each got.

#477 feat: Support for spoken punctuation and spoken emojis
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeResponse.java
  proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#478 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#479 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#480 deps: update dependency com.google.cloud:google-cloud-shared-dependencies to v0.21.0
  pom.xml
Labels: api: speech, cla: yes

#488 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#492 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#494 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#500 feat: add webm opus support
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#503 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#506 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#507 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes
