Repository googleapis/java-speech, pull requests merged in 2021-03, with the labels that each got.

#453 feat(generator): update protoc to v3.15.3
  proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionAudio.java
  proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/RecognitionAudioOrBuilder.java
  proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeRequest.java
  proto-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/StreamingRecognizeRequestOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudio.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudioOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeRequest.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognizeRequestOrBuilder.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#455 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#458 chore(release): update Java microgenerator to 1.0.1
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/SpeechSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/package-info.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/GrpcSpeechCallableFactory.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/GrpcSpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1/stub/SpeechStubSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/AdaptationClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/AdaptationSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/package-info.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/AdaptationStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/AdaptationStubSettings.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/GrpcAdaptationCallableFactory.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/GrpcAdaptationStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/GrpcSpeechCallableFactory.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/GrpcSpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/SpeechStub.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/stub/SpeechStubSettings.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/MockSpeech.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/MockSpeechImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/SpeechClientTest.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/AdaptationClientTest.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockAdaptation.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockAdaptationImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockSpeech.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockSpeechImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechClientTest.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/CustomClassName.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LocationName.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/PhraseSetName.java
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#460 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#461 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#462 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#463 chore: update gax-java dependency to 1.62
  grpc-google-cloud-speech-v1/src/main/java/com/google/cloud/speech/v1/SpeechGrpc.java
  grpc-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/AdaptationGrpc.java
  grpc-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechGrpc.java
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#466 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#467 feat: Support output transcript to GCS for LongRunningRecognize
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/AdaptationClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechClient.java
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/gapic_metadata.json
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/AdaptationClientTest.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeMetadata.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeMetadataOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeRequest.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeRequestOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudio.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionAudioOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfig.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/RecognitionConfigOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechAdaptationProto.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionResult.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechRecognitionResultOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResult.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/StreamingRecognitionResultOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/TranscriptOutputConfig.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/TranscriptOutputConfigOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech_adaptation.proto
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#471 feat: Support output transcript to GCS for LongRunningRecognize
  google-cloud-speech/src/main/java/com/google/cloud/speech/v1p1beta1/AdaptationClient.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1/MockSpeechImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockAdaptationImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/MockSpeechImpl.java
  google-cloud-speech/src/test/java/com/google/cloud/speech/v1p1beta1/SpeechClientTest.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeMetadata.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeMetadataOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeResponse.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/LongRunningRecognizeResponseOrBuilder.java
  proto-google-cloud-speech-v1p1beta1/src/main/java/com/google/cloud/speech/v1p1beta1/SpeechProto.java
  proto-google-cloud-speech-v1p1beta1/src/main/proto/google/cloud/speech/v1p1beta1/cloud_speech.proto
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#472 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#468 docs(samples): adds model adaptation sample
  samples/snippets/src/main/java/com/example/speech/SpeechModelAdaptationBeta.java
  samples/snippets/src/test/java/com/example/speech/SpeechModelAdaptationBetaTest.java
Labels: api: speech, cla: yes, samples

#473 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#474 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: speech, automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#475 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#476 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full
