Repository googleapis/java-speech, pull requests merged in 2021-05, with the labels that each got.

#509 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: none

#510 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: speech, automerge, cla: yes

#511 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: speech, cla: yes, context: full

#516 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#517 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#520 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#521 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#522 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes

#526 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#533 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: speech, automerge, cla: yes, context: full

#536 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: speech, automerge, cla: yes
